server:
  host: localhost
  port: 7233
  namespace: default
#  mtls: # Enable if mTLS is required
#    cert_path: "cert.crt"
#    key_path: "cert.key"
workers:
    # a Simple Worker registering 1 Workflow and 1 Activity returning strings
  - name: SimpleWorker
    task_queue: simple
    workflows:
      - type: HelloWorldWorkflow
        result: "Hello World"
    activities:
      - type: HelloWorldActivity
        result: "Hello World"
  # A Complex Worker registering 2 Workflow and 2 Activities returning object results
  - name: ComplexWorker
    task_queue: complex
    workflows:
      - type: HelloWorldWorkflow
        result:
          supportedLanguagesCount: 2
          supportedLanguages:
            - english
            - maltese
          messages:
            english: "Hello World"
            maltese: "Aw Dinja!"
      - type: GoodbyeWorldWorkflow
        result:
          supportedLanguagesCount: 2
          supportedLanguages:
            - english
            - maltese
          messages:
            english: "Goodbye World"
            maltese: "Ċaw Dinja!"
    activities:
      - type: HelloWorldActivity
        result:
          supportedLanguagesCount: 2
          supportedLanguages:
            - english
            - maltese
          messages:
            english: "Hello World"
            maltese: "Aw Dinja!"
      - type: GoodbyeWorldActivity
        result:
          supportedLanguagesCount: 2
          supportedLanguages:
            - english
            - maltese
          messages:
            english: "Goodbye World"
            maltese: "Ċaw Dinja!"