name: Release

on:
  push:
    tags:
      - 'v*'  # Matches any tag that starts with "v" (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: make test

      - name: Build binaries for release
        run: make release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/temporal-phantom-worker-darwin-amd64-v0.0.0-beta.tar.gz
            release/temporal-phantom-worker-linux-amd64-v0.0.0-beta.tar.gz
            release/temporal-phantom-worker-windows-amd64-v0.0.0-beta.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}